## References: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.BallTree.html

## 1) Query for k-nearest neighbors

In [21]:
from sklearn.neighbors import BallTree
import numpy as np
rng = np.random.RandomState(0)
X = rng.random_sample((10, 3))  # 10 points in 3 dimensions
tree = BallTree(X, metric="chebyshev")              
dist, ind = tree.query(X[:1], k=3)                
print(ind)  # indices of 3 closest neighbors

print(dist)  # distances to 3 closest neighbors

[[0 3 7]]
[[0.         0.16537199 0.25371   ]]


## 2) Pickle and Unpickle a tree

In [13]:
from sklearn.neighbors import BallTree
import numpy as np
import pickle
rng = np.random.RandomState(0)
X = rng.random_sample((10, 3))  # 10 points in 3 dimensions
tree = BallTree(X)        
s = pickle.dumps(tree)                     
tree_copy = pickle.loads(s)                
dist, ind = tree_copy.query(X[:1], k=3)     
print(ind)  # indices of 3 closest neighbors

print(dist)  # distances to 3 closest neighbors

[[0 3 1]]
[[0.         0.19662693 0.29473397]]
